---
title: "Ipomopsis temperature experiments: Floral traits"
author: "Carrie Wu, John Powers, David Hopp, Diane Campbell"
date: "`r Sys.Date()`"
output: 
  html_document:
    self_contained: no
    lib_dir: libs
    code_folding: hide
    toc: yes
    toc_float: TRUE 
editor_options: 
  chunk_output_type: console
---
<style type="text/css">
.main-container { max-width: 1000px; margin-left: 0; margin-right: auto; }
img{ max-width:200%; height: auto; }
td, th { padding : 6px }
</style>

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(knitr)
library(lme4)
library(lmerTest)
library(viridis)
knitr::opts_chunk$set(comment="", cache=T, warning=F, message=F, 
                      fig.path = "plots-traits/", dev="svglite", dev.args=list(fix_text_size=FALSE), 
                      fig.height=5, fig.width=5)
```

```{r read_data}
census.maxf <- read_csv("data/2021 Maxfield Rosettes - 2021OTCs.csv") %>% 
  mutate(across(c(plant, plot), as.character),
         temp=fct_relevel(fct_recode(temp,"warmed"="OTC"),"control"))

morph <- bind_rows(GNA=read_csv("data/traits/GNA floral traits - 2021.csv", na="."),
                SC=read_csv("data/traits/Spring Creek floral traits - 2021.csv", na="."), .id="site") %>% 
  rename(plantid = plant, temp = location, plotid=OTC) %>% drop_na(temp) %>% 
  mutate(temp=fct_relevel(fct_recode(temp,"warmed"="in", "control"="out"),"control")) %>% 
  bind_rows(read_csv("data/traits/2021 Maxfield Floral Traits - Morphology21.csv") %>% 
              mutate(plant = as.character(plant), site="Maxfield") %>% 
              left_join(census.maxf) %>% drop_na(plot)) %>% 
  mutate(species = if_else(site=="SC", "ten", "agg"))

nectar <- read_csv("data/traits/2021 Maxfield Floral Traits - Nectar21.csv") %>% 
  mutate(across(c(plant), as.character)) %>% 
  left_join(census.maxf) %>% 
  mutate(nectar_volume=nectar_48_h_mm*5/32,
         nectar_sugar=nectar_volume*nectar_conc,
         plantid=paste0(plotid,plant), 
         site="Maxfield", species="agg")

flrcol.raw <- read_csv("data/traits/2021 Maxfield Flower Color - 2021.csv", name_repair="minimal") %>% as.data.frame()
wl <- flrcol.raw[,1] #350:1000
flrcol.raw <- flrcol.raw[,seq(2,length(flrcol.raw),2)]

flrcol.long <- cbind(wl,stack(flrcol.raw)) %>% 
  mutate(red=wl>=626&wl<=700, #sum red and green regions to calculate redness index
         green=wl>=476&wl<=550,
         total=wl>=401&wl<=750,
         color=ifelse(red,"red",ifelse(green,"green",NA)))
flrcol.total <- flrcol.long %>% group_by(color,total,ind) %>% summarize(values=sum(values))

flrcol <- pivot_wider(flrcol.total,names_from=c("color","total"),values_from="values") %>% 
  mutate(total = green_TRUE+red_TRUE+NA_TRUE,
         redness = (red_TRUE-green_TRUE)/total,
         ind = str_replace(ind,fixed("."),"_")) %>% 
  separate(ind, into=c("plantid","rep"), sep="_", fill="right", remove=F) %>%
  mutate(rep=as.integer(replace_na(rep, "0"))+1) %>% 
  left_join(census.maxf) %>% mutate(site="Maxfield", species="agg")

phen.raw <- read_csv("data/traits/2021 Maxfield Phenology - 2021.csv")%>% 
  mutate(plot = as.character(plot), 
         plotid = paste0(plot, subplot),
         plantid = paste0(plotid, plant),
         plant = as.character(plant),
         julian = yday(date),
         year="2021",
         height_cm=as.integer(as.character(height_cm)),
         open = rowSums(select(., starts_with("open")), na.rm=T),
         buds = rowSums(select(., starts_with("buds")), na.rm=T),
         eggs = rowSums(select(., starts_with("eggs")), na.rm=T)) %>% 
  left_join(census.maxf) %>% 
  mutate_if(is.character, as.factor) 

#some plants were measured late, merge with the earlier date
phen.raw %>% count(date, plantid) %>% ggplot(aes(x=date, y=plantid))+ geom_tile()
phen <- phen.raw %>% mutate(date=ymd(recode(as.character(date),
                                             "2021-07-02"="2021-06-30", "2021-07-26"="2021-07-20")),
                            julian=yday(date)) %>% 
  complete(nesting(plantid, plotid, plot, subplot, snow, temp),nesting(julian, date), fill=list(open=0,buds=0)) %>% #add zeros to weeks the plant was not counted
  mutate(flowering = open + buds > 0,
         has_egg = eggs > 0, 
         site="Maxfield", species="agg")

spnames <- c(agg="I. aggregata", ten="I. tenuituba")
sitenames <- c(GNA="Gothic Natural Area",Maxfield="Maxfield Meadow",SC="Spring Creek")

alltraits <- c("corolla_length", "corolla_width", "nectar_volume", "nectar_conc", "nectar_sugar", 
               "height_cm", "redness", "prop_infested", "prop_aborted")
traitnames.units <- set_names(c(
  "Corolla length (mm)", "Corolla width (mm)",
  "Nectar production (\U00B5L/day)", "Nectar conc. (% by mass)", "Nectar sucrose (mg/day)",
  "Inflorescence height (cm)", "Redness index", 
  "Prop. nonaborted fruits infested","Prop. fruits aborted"), alltraits)
```

# Sample sizes

## Measurements per plant
```{r n_per_plant}
morph %>% drop_na(corolla_length) %>% count(site, plantid, name="n_per_plant") %>% count(site, n_per_plant) %>%
  kable(caption="corolla_length")
nectar %>% drop_na(nectar_volume) %>% count(site, plantid, name="n_per_plant") %>% count(site, n_per_plant) %>% 
  kable(caption="nectar_volume")
phen %>% drop_na(height_cm) %>% count(site, plantid, name="n_per_plant") %>% count(site, n_per_plant) %>% 
  kable(caption="height_cm")
flrcol %>% drop_na(redness) %>% count(site, plantid, name="n_per_plant") %>% count(site, n_per_plant) %>% 
  kable(caption="redness")
```

## Number of plants
```{r n_total}
morph %>% drop_na(corolla_length) %>% count(site, temp, plantid) %>% count(site, temp) %>% kable(caption="corolla_length")
nectar%>% drop_na(nectar_volume)  %>% count(site, temp, plantid) %>% count(site, temp) %>% kable(caption="nectar_volume")
phen  %>% drop_na(height_cm, temp)  %>% count(site, temp, plantid) %>% count(site, temp) %>% kable(caption="height_cm")
flrcol%>% drop_na(redness, temp)    %>% count(site, temp, plantid) %>% count(site, temp) %>% kable(caption="redness")

#Average data by plant
morph.mean <- morph %>% drop_na(corolla_length) %>% 
  group_by(species, site, temp, snow, plotid, plantid) %>%
  summarize(across(c(corolla_length, corolla_width), mean, na.rm=T), n = n())
nectar.mean <- nectar %>% drop_na(nectar_volume) %>% 
  group_by(species, site, temp, snow, plotid, plantid) %>%
  summarize(across(c(nectar_volume, nectar_conc, nectar_sugar), mean, na.rm=T), n = n())
phen.max <- phen %>% drop_na(height_cm, temp) %>% 
  group_by(species, site, temp, snow, plotid, plantid) %>% 
  summarize(height_cm=max(height_cm, na.rm=T)) #use the maximum plant height instead of the mean across the year (deer browsing)
flrcol.mean <- flrcol %>% drop_na(redness, temp) %>% 
  group_by(species, site, temp, snow, plotid, plantid) %>% 
  summarize(redness=mean(redness, na.rm=T))

all.mean <- morph.mean %>% rename(n.morph=n) %>% 
  full_join(rename(nectar.mean, n.nectar=n)) %>% full_join(phen.max) %>% full_join(flrcol.mean)
```


# Trait correlations
```{r corr}
ggplot(morph, aes(shape=site, y=corolla_width, x=corolla_length, color=temp)) + 
  facet_wrap(vars(species), labeller = as_labeller(spnames)) +
  geom_point() + geom_smooth(aes(group=species), color="black") + 
  labs(x="Corolla length", y="Corolla width", shape="Site", color="Temperature") + 
  scale_color_brewer(palette="Set1", direction=-1) + theme_bw() + 
  theme(strip.text=element_text(face="italic"))
ggplot(nectar, aes(y=nectar_conc, x=nectar_volume, color=temp)) + 
  geom_point() + geom_smooth(color="black") + 
  labs(x="Nectar volume (uL)", y="Nectar concentration", shape="Site", color="Temperature") + 
  scale_color_brewer(palette="Set1", direction=-1) + theme_bw() + 
  theme(strip.text=element_text(face="italic"))
```

# Trait plasticity
```{r plasticity_multisite, fig.height=7.5}
library(ggsignif)
morph.mean %>% pivot_longer(c(corolla_length, corolla_width)) %>% 
ggplot(aes(x=temp, y=value, color=temp)) + #paste(spnames[species], sitenames[site], sep="\n")
  facet_grid(name~site, scales="free_y", labeller = as_labeller(c(traitnames.units, sitenames)))+
  geom_violin(draw_quantiles=c(0.25, 0.5, 0.75)) + 
  geom_signif(comparisons = list(c(1,2)), 
              map_signif_level=TRUE, color="black",size=0.4, textsize=3) +
  geom_point(position=position_jitterdodge(dodge.width=0.9, jitter.width=0.1), size=1) +
  labs(x="", y="", color="Temperature") + 
  scale_y_continuous(limits=c(0,NA))+
  scale_color_brewer(palette="Set1", direction=-1) + theme_minimal() +
  theme(legend.position = "top", axis.title.x=element_blank(), axis.text.x=element_blank(),
        panel.grid.major.x = element_blank())
```

```{r plasticity, fig.width=7.5}
all.mean %>% pivot_longer(any_of(alltraits)) %>% 
  filter(site=="Maxfield", !name %in% c("corolla_length", "corolla_width", "nectar_sugar")) %>% 
  drop_na(value) %>% 
ggplot(aes(x=temp, y=value, color=temp)) + 
  facet_wrap(vars(name), scales="free_y", labeller = as_labeller(traitnames.units), nrow=1)+
  geom_violin(draw_quantiles=c(0.25, 0.5, 0.75)) + 
  geom_point(position=position_jitterdodge(dodge.width=0.9, jitter.width=0.1), size=1) +
  geom_signif(comparisons = list(c(1,2)), 
              map_signif_level=TRUE, color="black",size=0.4, textsize=3) +
  labs(x="", y="", color="Temperature") + 
  scale_y_continuous(limits=c(0,NA))+
  scale_color_brewer(palette="Set1", direction=-1) + theme_minimal() +
  theme(legend.position = "top", axis.title.x=element_blank(), axis.text.x=element_blank(),
        panel.grid.major.x = element_blank())
```


# Effect of snowmelt

```{r snow}
lmer(corolla_length~temp*snow+(1|plotid)+(1|plantid),data=filter(morph, site=="Maxfield")) %>% anova %>%
  kable(caption="corolla_length")
lmer(corolla_width ~temp*snow+(1|plotid)+(1|plantid),data=filter(morph, site=="Maxfield")) %>% anova %>%
  kable(caption="corolla_width")
lmer(nectar_volume ~temp*snow+(1|plotid)+(1|plantid),data=nectar) %>% anova %>% 
  kable(caption="nectar_volume")
lmer(nectar_conc   ~temp*snow+(1|plotid)+(1|plantid),data=nectar) %>% anova %>% 
  kable(caption="nectar_conc")
lmer(height_cm   ~temp*snow+(1|plotid),data=phen.max) %>% anova %>% 
  kable(caption="height_cm")
lmer(redness     ~temp*snow+(1|plotid)+(1|plantid), data=flrcol) %>% anova %>% 
  kable(caption="redness")
```

# Effect of temperature

```{r temp}
lmer(corolla_length~temp*species+(1|plantid),data=morph) %>% anova %>% kable(caption="corolla_length")
lmer(corolla_width ~temp*species+(1|plantid),data=morph) %>% anova %>% kable(caption="corolla_width")
lmer(nectar_volume ~temp+(1|plantid),data=nectar)        %>% anova %>% kable(caption="nectar_volume")
lmer(nectar_conc   ~temp+(1|plantid),data=nectar)        %>% anova %>% kable(caption="nectar_conc")
lm(height_cm     ~temp, data=phen.max)      %>% anova %>% kable(caption="height_cm")
lmer(redness       ~temp+(1|plantid), data=flrcol)       %>% anova %>% kable(caption="redness")
```

# Flower color

## Spectra

```{r flrcol_uv}
library(pavo)
# use human range to estimate perceived color (requires interpolated 300 nm data)
flrspec.human <- cbind(wl, flrcol.raw) %>% as.rspec(lim = c(300,700))#no UV data below 350 nm, interpolate
#plot(flrspec.human, col = turbo(ncol(flrspec)), main="Raw data")
#plot(flrspec.human, col = spec2rgb(flrspec.human), main="Raw data")
flrspec.human.nm <- procspec(flrspec.human, opt = c("smooth", "max"), span=0.08) #smooth and normalize
#plot(flrspec.human.nm, col = turbo(ncol(flrspec)), main="Divide by max")
flrspec.human.nm.zero <- procspec(flrspec.human.nm, fixneg="zero") #throw out negative reflectance
#plot(flrspec.human.nm.zero, col = turbo(ncol(flrspec)), main="Divide by max")
#plot(flrspec.human.nm.zero, col = spec2rgb(flrspec.human.nm.zero), main="Divide by max")
flrcol$RGB <- spec2rgb(flrspec.human.nm.zero)
```

```{r flrcol, dev="png", dev.args=list()}
ggplot(flrcol.long, aes(x=wl, y=values, color=ind)) + geom_line() + 
  annotate("rect", xmin=401, xmax=750, ymin=0, ymax=100, fill=NA, color="black", size=1) +
  annotate("rect", xmin=476, xmax=550, ymin=0, ymax=100, fill=NA, color="green", size=1) +
  annotate("rect", xmin=626, xmax=700, ymin=0, ymax=100, fill=NA, color="red", size=1) +
  labs(x="Wavelength (nm)", y="Reflectance (%)")+ guides(color="none") + theme_minimal() +
  scale_x_continuous(n.breaks=10, limits=c(350, 1000)) + scale_color_viridis_d(option="turbo")

plot_colranges <- function() {
  abline(v=476, lwd=2, col="green"); abline(v=550, lwd=2, col="green")
  abline(v=626, lwd=2, col="red");   abline(v=700, lwd=2, col="red")
  abline(v=401, lwd=2, col="black"); abline(v=750, lwd=2, col="black")
}

flrspec <- cbind(wl, flrcol.raw) %>% as.rspec(lim = c(401,750))
plot(flrspec, col = turbo(ncol(flrspec)), main="Raw data"); plot_colranges()
heatmap(t(as.matrix(flrspec)[,-1]), Rowv = NA, Colv=NA, scale="none", col=viridis(128), main="Raw data") #block of samples zeroed wrong?
ggplot(flrcol.total %>% mutate(index=row_number()), aes(x=index, y=values, color=paste(color, total))) +
  geom_point() + geom_smooth(span=0.2) + labs(x="Sample number", y="Summed reflectance", color="Wavelength range")+
  scale_color_manual(values=c("green", "grey50" ,"black","red"), 
                     labels=c("green","outside 400-750 nm", "other inside 400-750 nm", "red"))
ggplot(flrcol %>% mutate(index=row_number()), aes(x=index, y=redness)) +
  geom_point() + geom_smooth(span=0.3) + labs(x="Sample number", y="Redness")

flrspec.nm.zero <- procspec(flrspec, opt = c("smooth", "max"), span=0.08, fixneg="zero") #smooth, normalize, zero negatives
plot(flrspec.nm.zero, col = turbo(ncol(flrspec)), main="Divide by max"); plot_colranges()
heatmap(t(as.matrix(flrspec.nm.zero)[,-1]), Rowv = NA, Colv=NA, scale="none", col=viridis(128), main="Divide by max") #block fixed by normalizing
plot(flrspec.nm.zero, col = flrcol$RGB, main="Divide by max"); plot_colranges()
plot(flrspec.nm.zero, col = viridis(100)[300*(flrcol$redness-0.1)], main="Divide by max, color by redness"); plot_colranges()
flrspec.sum.zero <- procspec(flrspec, opt = c("smooth", "sum"), span=0.08, fixneg="zero") #smooth, normalize, zero negatives
plot(flrspec.sum.zero, col = viridis(100)[300*(flrcol$redness-0.1)], main="Divide by sum, color by redness"); plot_colranges()
```

## PCA
```{r flrcol_pca}
flrspec.nm.zero.bin <- procspec(flrspec.nm.zero, opt = c("bin", "center"), bins=16) 
rownames(flrspec.nm.zero.bin) <- flrspec.nm.zero.bin[,1]
library(vegan)
flrcol.pca <- rda(t(flrspec.nm.zero.bin[,-1]), scale = TRUE)
flrcol <- bind_cols(flrcol, scores(flrcol.pca, display="sites"))
plot(flrcol.pca, type="none", main=paste("PCA of", nrow(flrspec.nm.zero.bin),"wavelength bins"))
ordispider(flrcol.pca, flrcol$plantid, col="grey40")
points(flrcol.pca, display="sites", col=flrcol$RGB, pch=c(17,19)[flrcol$temp])
text(flrcol.pca, display="species", col="black", cex=0.8)

library(GGally)
ggpairs(select(flrcol, total, red_TRUE, green_TRUE, redness, PC1), 
        lower=list(continuous=wrap("smooth", method = "loess")))
```

## CAP
```{r flrcol_cap}
flrcol.cap <- capscale(t(flrspec.nm.zero.bin[,-1]) ~ temp, scale = TRUE, data=flrcol)
anova(flrcol.cap, by="term")
```

## Spectrum vs. temp

```{r flrcol_avg}
aggplot(procspec(flrspec, opt="smooth", span=0.08), flrcol$temp, legend= T, main="Raw data")
aggplot(flrspec.nm.zero, flrcol$temp, legend= T,main= "Divided by max")
aggplot(flrspec.sum.zero, flrcol$temp, legend= T, main="Divided by sum")
```


# Phenology and fly eggs

## Snowmelt effects

```{r phenology_snow}
phen %>% drop_na(snow,temp) %>% group_by(snow, temp, julian) %>% summarize_at(c("open","buds"), mean, na.rm=T) %>% 
  ggplot(aes(x=julian, y=open, shape=snow, linetype=snow, color=temp))+ geom_point() + 
  geom_path(aes(group=paste(snow, temp))) +
  labs(y="Mean total flowers", 
       x="Day of year", color="Temperature", shape="Snowmelt", linetype="Snowmelt") +
  scale_x_continuous(breaks=seq(120,240, by=20))+
  scale_color_brewer(palette="Set1", direction=-1) +
  scale_linetype_manual(values=c(2,1)) + theme_minimal() + 
  theme(legend.key.size = unit(2, "lines"))

phen %>% drop_na(snow,temp)%>% group_by(snow, temp, julian) %>% summarize_at("flowering", mean, na.rm=T) %>% 
  ggplot(aes(x=julian, y=flowering, shape=snow, linetype=snow, color=temp))+ geom_point() + 
  geom_path(aes(group=paste(snow, temp))) +
  labs(y="Proportion flowering", 
       x="Day of year", color="Temperature", shape="Snowmelt", linetype="Snowmelt") +
  scale_x_continuous(breaks=seq(120,240, by=20))+
  scale_y_continuous(labels = scales::percent)+
  scale_color_brewer(palette="Set1", direction=-1) +
  scale_linetype_manual(values=c(2,1)) + theme_minimal() + 
  theme(legend.key.size = unit(2, "lines"))

phen %>% drop_na(snow,temp)%>% group_by(snow, temp, julian) %>% summarize_at("eggs", mean, na.rm=T) %>% 
  ggplot(aes(x=julian, y=eggs, shape=snow, linetype=snow, color=temp))+ geom_point() + 
  geom_path(aes(group=paste(snow, temp))) +
  labs(y="Mean total eggs", 
       x="Day of year", color="Temperature", shape="Snowmelt", linetype="Snowmelt") +
  scale_x_continuous(breaks=seq(120,240, by=20))+
  scale_color_brewer(palette="Set1", direction=-1) +
  scale_linetype_manual(values=c(2,1)) + theme_minimal() + 
  theme(legend.key.size = unit(2, "lines"))

phen%>% drop_na(snow,temp) %>% group_by(year, snow, temp, julian) %>% summarize_at("has_egg", mean, na.rm=T) %>% 
  ggplot(aes(x=julian, y=has_egg, shape=snow, linetype=snow, color=temp))+ geom_point() + 
  geom_path(aes(group=paste(snow, temp))) +
  labs(y="Proportion of plants with eggs", 
       x="Day of year", color="Temperature", shape="Snowmelt", linetype="Snowmelt") +
  scale_x_continuous(breaks=seq(120,240, by=20))+
  scale_y_continuous(labels = scales::percent)+
  scale_color_brewer(palette="Set1", direction=-1) +
  scale_linetype_manual(values=c(2,1)) + theme_minimal() + 
  theme(legend.key.size = unit(2, "lines"))
```

## Temperature effects

```{r phenology_temp}
ggplot(phen %>% drop_na(height_cm, temp), aes(x=julian, y=height_cm, color=temp))+ geom_point() + geom_path(aes(group=plantid))+
  labs(y="Plant height", x="Day of year", color="Temperature") +
  scale_x_continuous(breaks=seq(120,240, by=20))+ 
  scale_color_brewer(palette="Set1", direction=-1) +theme_minimal() 

phen %>% drop_na(snow,temp) %>% group_by(temp, julian) %>% drop_na(open, buds) %>% 
  summarize(openbuds.se = sd(open+buds)/sqrt(length(open+buds)), openbuds=mean(open+buds)) %>% 
  ggplot(aes(x=julian, y=openbuds, color=temp))+ geom_point() + 
  geom_path(aes(group=temp)) + geom_linerange(aes(ymin=openbuds-openbuds.se, ymax=openbuds+openbuds.se))+
  labs(y="Mean total open flowers + elongated buds", 
       x="Day of year", color="Temperature") +
  scale_x_continuous(breaks=seq(120,240, by=20))+
  scale_color_brewer(palette="Set1", direction=-1) + theme_minimal()
lmer(I(open+buds) ~ factor(date) * temp + (1|plantid), data=phen.raw) %>% anova %>% kable(caption="mean open and buds")

phen %>% drop_na(temp)%>% group_by(temp, julian) %>% summarize_at("flowering", mean, na.rm=T) %>% 
  ggplot(aes(x=julian, y=flowering, color=temp))+ geom_point() + 
  geom_path(aes(group=temp)) + 
  labs(y="Proportion flowering", 
       x="Day of year", color="Temperature") +
  scale_x_continuous(breaks=seq(120,240, by=20))+
  scale_y_continuous(labels = scales::percent)+
  scale_color_brewer(palette="Set1", direction=-1) + theme_minimal()

phen %>% drop_na(temp) %>% group_by(temp, julian) %>% drop_na(eggs) %>% 
  summarize(eggs.se = sd(eggs)/sqrt(length(eggs)), eggs=mean(eggs)) %>% 
  ggplot(aes(x=julian, y=eggs, color=temp))+ geom_point() + 
  geom_path(aes(group=temp)) + geom_linerange(aes(ymin=eggs-eggs.se, ymax=eggs+eggs.se))+
  labs(y="Mean total eggs", 
       x="Day of year", color="Temperature") +
  scale_x_continuous(breaks=seq(120,240, by=20))+
  scale_color_brewer(palette="Set1", direction=-1) + theme_minimal() 
lmer(eggs ~ factor(date) * temp + (1|plantid), data=phen.raw) %>% anova %>% kable(caption="mean eggs")

phen %>% drop_na(temp) %>% group_by(year, temp, julian) %>% summarize_at("has_egg", mean, na.rm=T) %>% 
  ggplot(aes(x=julian, y=has_egg, color=temp))+ geom_point() + 
  geom_path(aes(group=temp)) +
  labs(y="Proportion of plants with eggs", 
       x="Day of year", color="Temperature") +
  scale_x_continuous(breaks=seq(120,240, by=20))+
  scale_y_continuous(labels = scales::percent)+
  scale_color_brewer(palette="Set1", direction=-1) + theme_minimal() 
```
